//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUKSI
    {
        public int iId { get; set; }
        public Nullable<int> iSenin { get; set; }
        public Nullable<int> iSelasa { get; set; }
        public Nullable<int> iRabu { get; set; }
        public Nullable<int> iKamis { get; set; }
        public Nullable<int> iJumat { get; set; }
        public Nullable<int> iSabtu { get; set; }
        public Nullable<int> iMinggu { get; set; }
        public Nullable<int> iSeninFix { get; set; }
        public Nullable<int> iSelasaFix { get; set; }
        public Nullable<int> iRabuFix { get; set; }
        public Nullable<int> iKamisFix { get; set; }
        public Nullable<int> iJumatFix { get; set; }
        public Nullable<int> iSabtuFix { get; set; }
        public Nullable<int> iMingguFix { get; set; }
        public System.DateTime dCreatedAt { get; set; }
        public int iIsActive { get; set; }
        public System.DateTime dCreatedDate { get; set; }
        public Nullable<System.DateTime> dModifiedDate { get; set; }
    }
}
